[project]
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "migration"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bcftools = ">=1.21,<2"
polars = ">=1.24.0,<2"
