[project]
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "ARG"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
uv = ">=0.7.13,<0.8"
pip = ">=25.1.1,<26"
pysam = ">=0.23.3,<0.24"
shapeit5 = ">=5.1.1,<6"
